
[config]
additional_profiles = [
    "docs-all-modification-tasks",
    "ci-coverage-tasks",
    "ci-all-build-tasks",
    "ci-static-code-analysis-tasks",
    "publish-pre-cleanup"
]

[tasks.clean-target-test-directory]
script = [
'''
#!@duckscript
rm -Rf ./target/__test
'''
]

[tasks.pre-test]
dependencies = [
    "clean-target-test-directory"
]
